# Generated by Django 3.0.14 on 2021-12-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(auto_created=True, db_column='emp_id', primary_key=True, serialize=False)),
                ('firstName', models.CharField(db_column='first_name', max_length=100)),
                ('lastName', models.CharField(db_column='last_name', max_length=100)),
                ('middleName', models.CharField(db_column='middle_name', max_length=100, null=True)),
                ('dob', models.DateField()),
                ('dateOfJoining', models.DateField(db_column='date_of_joining')),
            ],
        ),
    ]
