# Generated by Django 3.0.14 on 2021-12-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptName', models.CharField(db_column='dept_name', max_length=100, unique=True)),
                ('deptContactPerson', models.CharField(max_length=100)),
            ],
        ),
    ]
