# Generated by Django 3.0.14 on 2021-12-11 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee_deptid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='deptId',
            field=models.ForeignKey(db_column='dept_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Department'),
        ),
    ]
