# Generated by Django 3.0.14 on 2021-12-11 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211211_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.IntegerField(auto_created=True, db_column='Des_id', primary_key=True, serialize=False)),
                ('designationName', models.CharField(db_column='Des_name', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='desid',
            field=models.ForeignKey(db_column='des_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Designation'),
        ),
    ]
