# Generated by Django 3.0.14 on 2021-12-13 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_punchindetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.IntegerField(auto_created=True, db_column='project_id', primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(db_column='project_name', max_length=50)),
                ('ProjectIncharge', models.CharField(db_column='project_incharge', max_length=50)),
                ('ProjectStartDate', models.DateField(db_column='project_start_date')),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='desid',
            new_name='desId',
        ),
        migrations.CreateModel(
            name='EmployeetoProject',
            fields=[
                ('id', models.IntegerField(auto_created=True, db_column='Emp_Project_id', primary_key=True, serialize=False)),
                ('ProjectId', models.ForeignKey(db_column='Project_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ProjectDetails')),
                ('empId', models.ForeignKey(db_column='emp_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='projectId',
            field=models.ForeignKey(db_column='Project_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ProjectDetails'),
        ),
    ]
