# Generated by Django 3.0.14 on 2021-12-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211213_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='id',
            field=models.AutoField(auto_created=True, db_column='project_id', primary_key=True, serialize=False),
        ),
    ]
