# Generated by Django 3.0.14 on 2021-12-14 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211214_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='Assi_id', primary_key=True, serialize=False)),
                ('assignmentName', models.CharField(db_column='assignment_Name', max_length=100)),
                ('assignmentTopic', models.CharField(db_column='assignment_Topic', max_length=100)),
                ('assignmentStartDate', models.DateField(db_column='assignment_start_date')),
                ('assignmentEndDate', models.DateField(db_column='assignment_end_date', null=True)),
                ('employeeId', models.ForeignKey(db_column='emp_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Employee')),
            ],
        ),
    ]
