# Generated by Django 3.0.14 on 2021-12-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.CharField(db_column='topic_name', max_length=100)),
                ('topicDesc', models.CharField(db_column='topic_desc', max_length=1000)),
            ],
        ),
    ]
