# Generated by Django 3.0.14 on 2021-12-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routineName', models.CharField(db_column='routine_name', max_length=100)),
                ('topicDesc', models.CharField(db_column='routine_desc', max_length=1000)),
            ],
        ),
    ]
