# Generated by Django 3.0.14 on 2021-12-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_routine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='topicDesc',
            new_name='routineDesc',
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, db_column='emp_id', primary_key=True, serialize=False),
        ),
    ]
