# Generated by Django 3.0.14 on 2021-12-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211216_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newproject',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='Newproject_id', primary_key=True, serialize=False)),
                ('NewprojectName', models.CharField(db_column='newproject_name', max_length=100)),
                ('NewprojectIncharge', models.CharField(db_column='Newproject_incharge', max_length=50)),
                ('NewprojectStartDate', models.DateField(db_column='Newproject_Start_Date')),
            ],
        ),
    ]
