# Generated by Django 3.0.14 on 2021-12-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_newproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Salary',
            field=models.DecimalField(db_column='Emp_salary', decimal_places=6, default=0, max_digits=19),
            preserve_default=False,
        ),
    ]
