# Generated by Django 3.0.14 on 2021-12-30 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_employee_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Salary',
            new_name='salary',
        ),
        migrations.CreateModel(
            name='EmployeeAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='EmpAdd_id', primary_key=True, serialize=False)),
                ('EmpState', models.CharField(db_column='Employee_State', max_length=100)),
                ('EmpDistrict', models.CharField(db_column='Employee_District', max_length=100)),
                ('EmpContact', models.IntegerField(db_column='Emp_contact')),
                ('empid', models.ForeignKey(db_column='Emp_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Employee')),
            ],
        ),
    ]
